name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.20.4
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          go mod download
          go mod vendor

      - name: Test
        run: go test -v -cover ./...